- name: Create Local Environement
  hosts: localhost
  tasks:
    - name: Install Vagrant
      command: brew install hashicorp/tap/hashicorp-vagrant
    - name: init vagrant
      command: vagrant init
    - name: Copy Vagrantfile
      template:
        src: Vagrantfile.j2
        dest: Vagrantfile
    - name: Go to the folder and create the 2 Vms
      command: vagrant up

- name: Front Container deploy
  hosts: front
  become: true
  become_method: sudo
  roles: 
    - ROLE_FRONT
- name: Back Container deploy
  hosts: back
  become: true
  become_method: sudo
  roles: 
    - ROLE_BACK